config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get 'about', to: 'pages#about'
  #get 'courses/new', to: 'courses#new'
  #get 'students', to: 'students#index'
  resources :courses, except:[:destroy]
  resources :students, except:[:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
  delete 'course_drop', to: 'student_courses#destroy'
  get 'mentors', to:'students#mentors'
  #get '/courses/search', to: 'courses#search', as: 'search_courses'
  get 'search_courses', to: 'courses#search'
  get 'search_students', to: 'students#search'
  get "/students/confirm/:token", to: "students#confirm", as: "confirm_user"
  get '/students/admin_confirm/:id', to: "students#admin_confirm", as: "admin_confirm"
  get '/students/delete/:id', to: "students#destroy", as: "delete_student"
end

app/models/student.rb
class Student < ApplicationRecord

  before_save { self.email=email.downcase }
  validates :name, presence: true,length:{minimum:5,maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@amenitiz\.com\z/i

  validates :email,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: { maximum: 105 },
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses

  before_create :generate_confirmation_token

  def generate_confirmation_token
    self.confirmation_token = SecureRandom.urlsafe_base64.to_s
  end

  #after_create :send_confirmation_email

  def send_confirmation_email
    puts 'Send confirmation email'
    UserMailer.confirmation_email(self).deliver
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

skip_before_action :require_user, only: [:new, :create]

before_action :set_student, only: [:show,:edit,:update,:destroy]
before_action :require_same_student, only: [:edit,:update]
before_action :require_admin, only: [:destroy]



  def index
    #returns students with at least one active course
    #@students= Student.joins(:student_courses).where.not(student_courses: {student_id: nil})
    @students=Student.all
  end

  def new
    @student=Student.new
  end

  def create
    @student=Student.new(student_params)
    if @student.save
      user_mailer = UserMailer.new
      user_mailer.confirmation_email(Student.last).deliver
      flash[:notice]="You have succesfully signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show

  end

  def edit

  end

  def mentors
    @students= Student.where(is_mentor: true)
  end

  def update
    @student.name=params[:name]
    if @student.update(student_params)
      flash[:notice]="Update Succesfully saved"
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    if @student.destroy
      flash[:notice]="User Succesfully deleted"
      redirect_to students_path
    else
      flash[:notice]="There was an error when deleting"
      render students_path
    end
  end

  def search
    if params[:search_scope]=='false'
      @students=Student.where("name like :search OR skills like :search OR interests like :search", search: "%#{params[:search]}%")
   else
      @students=Student.where("name like :search OR skills like :search OR interests like :search", search: "%#{params[:search]}%").where(is_mentor: true)
   end
    if @students.count>0
      render 'index'
    else
      flash[:notice]="No matches found with your seach criteria"
      redirect_to students_path
    end
  end

  def confirm
    user = Student.find_by(confirmation_token: params[:token])
    if user
      user.update(confirmed: true)
      redirect_to root_url, notice: "Your account has been confirmed"
    else
      redirect_to root_url, alert: "Invalid Token"
    end
  end


  def admin_confirm
    user = Student.find(params[:id])
    if user
      user.update(confirmed: true)
      redirect_to students_path, notice: "#{user.name} has been confirmed"
    else
      redirect_to students_path, alert: "There was an error when confirming user"
    end
  end

  private

  def student_params
    params.require(:student).permit(:name,:email,:password,:password_confirmation,:is_mentor,:role,:domain,:team,:skills,:interests,:confirmed,:confirmation_token)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    if current_user!= @student && !is_admin?
      flash[:notice]="You can only edit your own profile"
      redirect_to student_path(current_user)
    end
  end

  def require_admin
    if !is_admin?
      flash[:notice]="You don't have privileges to perform this action"
      redirect_to student_path(current_user)
    end

  end



end

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%=  @student.new_record? ? "Sign Up" : "Edit Profile" %></h3>
        <div class="row">
          <%= form_for(@student,html: {class: "col s12"}) do |f| %>
          <div class="row">
            <div class="input-field col s4">
              <label>Want to be a Mentor?</label><%= f.select :is_mentor, options_for_select([["Nope, just Mentee by now", "false"], ["Sure. Let's share!", "true"]]),{ :selected => @student.is_mentor},class: "select-mentor" %>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true%>
              <%= f.label :name,"Enter your full name", class: "active" %>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <% if @student.new_record? || is_admin? %>
                <%= f.text_field :email, placeholder: "Enter your Email Address"  %>
              <% else %>
                <%= f.text_field :email, readonly: true  %>
              <% end %>
                <%= f.label :email,"Enter your Email Address", class: "active" %>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :role, placeholder: "Enter your current Role" %>
              <%= f.label :role,"Enter your current Role", class: "active" %>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s6">
              <%= f.text_field :domain, placeholder: "Enter you Domain" %>
              <%= f.label :domain,"Enter you Domain",class: "active" %>
            </div>
            <div class="input-field col s6">
              <%= f.text_field :team, placeholder: "Enter your Team" %>
              <%= f.label :team,"Enter your Team", class: "active" %>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :skills, placeholder: "Enter between commas the topics you can mentor about" %>
              <%= f.label :skills,"Topics you can mentor", class: "active" %>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :interests, placeholder: "Enter between commas the topics you want to learn about" %>
              <%= f.label :interests,"Topics you want to learn", class: "active" %>
            </div>
          </div>
          <% if @student.new_record? %>
            <div class="row">
              <div class="input-field col s6">
                <%= f.password_field :password, placeholder: "Choose a password" %>
                <%= f.label :password,"Choose a password",class: "active" %>
              </div>
              <div class="input-field col s6">
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password" %>
                <%= f.label :password_confirmation,"Confirm your password", class: "active" %>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="input-field col s12">
              <%= f.button(@student.new_record? ? '<i class="material-icons right">fast_forward</i>Sign Up'.html_safe : '<i class="material-icons right">fast_forward</i>Submit Changes'.html_safe, class: "btn orange waves-effect waves-light right") %>
            </div>
          </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/_results.html.erb
<div class="row">
  <% @students.each do |student|  %>

    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= student.name%>
            <% if student.is_mentor? %>
            <%='<i class="material-icons right icon-blue">gps_fixed</i>'.html_safe %>
          <% end %>
        </span>
          <p><a href="mailto:<%= student.email %>"><%= student.email%></a></p>
          <% if student.role!=nil && student.role!='' %>
            <p><%=student.role%> @ <%=student.domain%>::<%=student.team%></p>
          <% else %>
           <p>NoRole @ NoDomain::NoTeam</p>
          <% end %>
          <ul>Enroled Courses: <%= student.courses.count %>
            <!--
              TODO: REVIEW CSS TO KEEP CARD SIZE WHEN ADDING COURSES DETAILS
              <% student.courses.each do |course| %>
            <li> - <%= course.name %></li>
            <% end %>-->
          </ul>
        </div>
        <div class="card-action">
          <%= link_to "View Profile", student_path(student) %>
          <% if is_admin? %>
            <% if !student.confirmed %>
              <%= link_to "Confirm User", admin_confirm_path(student)%>
              <% end %>
            <%= link_to "Delete User", delete_student_path(student), class: "delete",data: { confirm: "Are you sure?. This action can't be undone",confirm_title: "User Deletion" } %>
          <% end %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s-12">
    <h4 class="center-align">Teammates</h4>
  </div>
</div>
<div class="row">
    <div class="col s-12">
      <%= form_tag search_students_path, method: :get do %>
      <p>
      <% if params[:search_scope].nil? ||  params[:search_scope]=='false' %>
          <label>
            <input name="search_scope" type="radio" value="false" checked />
            <span>All members</span>
          </label>
          <label>
            <input name="search_scope" type="radio" value="true" />
            <span>Only mentors</span>
          </label>&nbsp;
      <% else %>
        <label>
          <input name="search_scope" type="radio" value="false" />
          <span>All members</span>
        </label>
        <label>
          <input name="search_scope" type="radio" value="true" checked/>
          <span>Only mentors</span>
        </label>&nbsp;
      <% end %>
      </p>

        <%= label_tag "Search by name, skills or interests" %>
      <%= label_tag "Search by name, skills or interests" %>
        <%= text_field_tag :search, params[:search],class: "finder" %>
        <%= submit_tag "Search" %>
     <% end %>
    <!-- </p>-->
     </div>

</div>

<%= render 'results' %>

app/views/students/mentors.html.erb
<div class="row">
  <div class="col s-6">
    <h3 class="center-align">Mentors </h3>
  </div>

</div>

<div class="row">
  <% @students.each do |student|  %>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= student.name%>
          <% if student.is_mentor? %>
          <%='<i class="material-icons right icon-yellow">gps_fixed</i>'.html_safe %>
        <% end %>
      </span>
        <p><a href="mailto:<%= student.email %>"><%= student.email%></a></p>
        <p>Since: <%=student.created_at %></p>
        <% if student.role!=nil && student.role!='' %>
          <p><%=student.role%> at <%=student.domain%>::<%=student.team%></p>
        <% else %>
          <br>
        <% end %>
        <p>Course Enrolments: None</p>
      </div>
      <div class="card-action">
        <%= link_to "View Profile", student_path(student) %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/students/show.html.erb
<div class="row  sign-up-form">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @student.name%>
          <% if @student.is_mentor? %>
            <%='<i class="material-icons right icon-yellow">gps_fixed</i>'.html_safe %>
          <% end %>
        </span>
        <p>Email: <%= @student.email%></p>
        <p><%=@student.role%> at <%=@student.domain%>::<%=@student.team%></p>
        <p>Since: <%=@student.created_at %></p>
        <br>
        <% if !@student.skills.nil? %>
          <p>Topics she/he can Mentor: </p>

              <% @student.skills.split(",").each do |skill| %>
                <span class="skill">#<%= skill.lstrip %></span>
              <% end %>

        <% end %>

        <% if !@student.interests.nil? %>
          <p>Topics she/he would like to learn: </p>

            <% @student.interests.split(",").each do |interest| %>
            <span class="skill"> #<%= interest.lstrip %></span>
            <% end %>

        <% end %>
        <br>
        <p class="underline">Course Enrolments:
          <% if @student.courses.empty? %>
            None
          <% else %>
          <ul>
            <% @student.courses.each do |course| %>
            <li> - <%= course.name %>&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "Leave", course_drop_path(course_id: course.id), class: "waves-effect waves-light btn leave", method: :delete %></li>
            <% end %>
          </ul>
          <%end %>
        </p>
      </div>
    </div>
    <% if current_user == @student || is_admin? %>
     <%= link_to '<i class="material-icons right">create</i>Edit profile'.html_safe, edit_student_path(@student),class: "waves-effect waves-light btn-large" %>
    <% end %>
  </div>
</div>