config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get 'about', to: 'pages#about'
  #get 'courses/new', to: 'courses#new'
  #get 'students', to: 'students#index'
  resources :courses, except:[:destroy]
  resources :students, except:[:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
  delete 'course_drop', to: 'student_courses#destroy'
  get 'mentors', to:'students#mentors'
  #get '/courses/search', to: 'courses#search', as: 'search_courses'
  get 'search_courses', to: 'courses#search'
  get 'search_students', to: 'students#search'
  get "/students/confirm/:token", to: "students#confirm", as: "confirm_user"
  get '/students/admin_confirm/:id', to: "students#admin_confirm", as: "admin_confirm"
  get '/students/delete/:id', to: "students#destroy", as: "delete_student"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  skip_before_action :require_user
  before_action :set_course, only: [:show,:edit,:update]

  def index
    @courses=Course.all
    #@courses=Course.where('session_date > ?', DateTime.now)

  end

  def new
    @course=Course.new
  end

  def create
    @course=Course.new(course_params)
    if @course.save
      flash[:notice]="Your course was successfully created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def search
    @courses=Course.where("short_name like :search OR name like :search OR description like :search OR keywords like :search", search: "%#{params[:search]}%")
    if @courses.count>0
      render 'index'
    else
      flash[:notice]="No matches found with your seach criteria"
      redirect_to root_path
    end
  end

  def update
    if @course.update(course_params)
      flash[:notice]="Update Succesfully saved"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show

  end


  private

  def course_params
    params.require(:course).permit(:short_name,:name,:description,:mentor_id,:keywords,:max_attendants,:session_date)
  end

  def set_course
    #puts "Entro en before action"
    @course=Course.find(params[:id])
  end


end

app/views/courses/_form.html.erb
<%= render 'shared/errors', obj: @course %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%=  @course.new_record? ? "New Course" : "Edit Course" %></h3>
        <div class="row">
          <%= form_for(@course,html: {class: "col s12"}) do |f| %>
          <div class="row"> 
            <div class="input-field col s12">
              <%= f.text_field :short_name, placeholder: "Enter a short name", autofocus: true%>  
              <%= f.label :short_name, class: "active" %>
            </div>
          </div>
          <div class="row"> 
            <div class="input-field col s12">
              <%= f.text_field :name, placeholder: "Enter a name", autofocus: true%>  
              <%= f.label :name, class: "active" %>
            </div>
          </div>
          <div class="row"> 
            <div class="input-field col s12">  
              <%= f.text_area :description, placeholder: "Enter course description" %>
              <%= f.label :description, class: "active" %>
            </div>
          </div>
          <%= f.hidden_field :mentor_id, :value => current_user.id %>
        
          <div class="row"> 
            <div class="input-field col s12">  
              <%= f.text_field :max_attendants, placeholder: "Enter desired max attendants" %>
              <%= f.label :max_attendants, class: "active" %>
            </div>
          </div>

          <div class="row"> 
            <div class="input-field col s12">  
              <%= f.text_field :keywords, placeholder: "Enter between commas the keywords" %>
              <%= f.label :keywords, class: "active" %>
            </div>
          </div>

          <div class="row"> 
            <div class="input-field col s12">  
              <%= f.datetime_select :session_date, :ampm => false, :minute_step => 15 %>
              <%= f.label :session_date, class: "active" %>
            </div>
          </div>

          
          <div class="row"> 
            <div class="input-field col s12"> 
              <%= f.button(@course.new_record? ? '<i class="material-icons right">fast_forward</i>Create Course'.html_safe : '<i class="material-icons right">fast_forward</i>Submit Changes'.html_safe, class: "btn orange waves-effect waves-light right") %>
            </div>
          </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<div class="row">
  <div class="col s6">
    <h4 class="left-aligned">Coming Worksessions</h4>
  </div>
  <div class="col s6 right-aligned">
    <%= form_tag search_courses_path, method: :get do %>
      <%= text_field_tag :search, params[:search],class: "finder" %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col s6">
  </div>
  <div class="col s6 right-aligned">
    <% if logged_in? && current_user.is_mentor? %>
      <span class="right-aligned"> <%= link_to "+ ADD WORKSESSION", new_course_path %></span>
    <% end %>
  </div>
</div>

<div class="row">
  <% @courses.each do |course|  %>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= course.short_name%> : <%=course.name %></span>
        <% if logged_in? && course.mentor_id==current_user.id %>
          <p>Facilitator: You </p>
        <% else %>
          <p>Facilitator: <%=Student.find(course.mentor_id).name %></p>
        <% end %>
        <p>When: <%=course.session_date %></p>
        <p>Max attendants: <%= course.max_attendants %>
          <%if course.students.count>=course.max_attendants%>
          (ALL SEATS BOOKED ALREADY!!)
          <% else %>
          (<%=course.students.count%> seats already taken)
          <% end %>
        </p>
        <br>
        <p><i><%=course.description.truncate(100) %></i></p>
        <br>
        <p>Keywords</p>
        <% if !course.keywords.nil? %>
            <%course.keywords.split(",").each do |keyword| %>
              <span class="skill">#<%= keyword.lstrip %></span>
            <% end %>
           <% end %>

      </div>
      <div class="card-action">
        <% if logged_in? %>
          <% if !(current_user.courses.include?(course))%>
            <% if course.mentor_id!=current_user.id && course.students.count<course.max_attendants %>
              <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
            <% else %>
              <%= link_to "Edit Course",edit_course_path(course)%>
            <% end %>
          <%else%>
            <%= link_to "Leave Course", course_drop_path(course_id: course.id), method: :delete %>
          <% end %>
        <% end %>
        <%= link_to "Info", course_path(id: course.id)%>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<div class="row">
  <div class="col s6 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @course.short_name%> : <%=@course.name %></span>
        <% if logged_in? && @course.mentor_id==current_user.id %>
          <p>Facilitator: You </p>
        <% else %>
          <p>Facilitator: <%=Student.find(@course.mentor_id).name %></p>
        <% end %>
        <p>When: <%=@course.session_date %></p>
        <p>Max attendants: <%= @course.max_attendants %>
          <%if @course.students.count>=@course.max_attendants%>
          (ALL SEATS BOOKED ALREADY!!)
          <% else %>
          (<%=@course.students.count%> seat/s already taken)
          <% end %>
        </p>
        <br>
        <p class="underline">Enroled teammates:
            <% if @course.students.empty? %>
              None
            <% else %>
            <ul>
              <% @course.students.each do |student| %>
              <li> - <%= link_to student.name, student_path(student) %></li>
              <% end %>
            </ul>
            <%end %>
          </p>
        <br>
        <p class="underline">Keywords</p>
        <% if !@course.keywords.nil? %>
            <%@course.keywords.split(",").each do |keyword| %>
              <span class="skill">#<%= keyword.lstrip %> </span>
            <% end %>
        <% end %>
        <p class="underline">What is it about?</p>
        <p><i><%=@course.description %></i></p>
      </div>
      <div class="card-action">
        <% if logged_in? %>
          <% if !(current_user.courses.include?(@course))%>
            <% if @course.mentor_id!=current_user.id && @course.students.count<@course.max_attendants %>
              <%= link_to "Enroll", course_enroll_path(course_id: @course.id), method: :post %>
            <% else %>
              <%= link_to "Edit Course",edit_course_path(@course)%>
            <% end %>
          <%else%>
            <%= link_to "Leave Course", course_drop_path(course_id: @course.id), method: :delete %>
          <% end %>   
        <% end %>  
        <%= link_to "Back to Courses", root_path %>
      </div>
    </div>
  </div>
</div>