config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get 'about', to: 'pages#about'
  #get 'courses/new', to: 'courses#new'
  #get 'students', to: 'students#index'
  resources :courses, except:[:destroy]
  resources :students, except:[:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
  delete 'course_drop', to: 'student_courses#destroy'
  get 'mentors', to:'students#mentors'
  #get '/courses/search', to: 'courses#search', as: 'search_courses'
  get 'search_courses', to: 'courses#search'
  get 'search_students', to: 'students#search'
  get "/students/confirm/:token", to: "students#confirm", as: "confirm_user"
  get '/students/admin_confirm/:id', to: "students#admin_confirm", as: "admin_confirm"
  get '/students/delete/:id', to: "students#destroy", as: "delete_student"
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
 <!-- <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Mentoring Program</h5>
        <p class="grey-text text-lighten-4">The future of Knownledge Sharing.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </div>-->
  <div class="footer-copyright">
    <div class="container">
    © 2023 Amenitiz Learning Programs
    <a class="grey-text text-lighten-4 right" href="#!">Help</a>
    <a class="grey-text text-lighten-4 right footer-space" href="#!">Contact Us</a>
    <a class="grey-text text-lighten-4 right footer-space" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
  <li><%= session_link %></li>
  <% if logged_in? %>
    <li><%= link_to "Profile", student_path(current_user) %></li>
  <% else %>
    <li><%= link_to "Sign-up", new_student_path %></li>
  <% end %>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
      <li><%= link_to "Profile", student_path(current_user) %></li>
    <% else %>
      <li><%= link_to "Sign-up", new_student_path %></li>
    <% end %>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "Amenitiz Mentoring Program", root_path, class: "brand-logo right"%>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>  
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%=link_to "Worksessions", root_path %></li>
          <% if logged_in? %>
           <li><%=link_to "Members", students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">
            <% if logged_in? %>
              <% if is_admin? %>
                <%= current_user.name %> (admin) 
              <% else %>
                <%= current_user.name %>
              <% end %>
            <% else %>
              Account
            <% end %>
            <i class="material-icons right">arrow_drop_down</i></a></li>  
        </ul>
        <ul class="sidenav" id="mobile-demo">
          <li><%=link_to "Courses", root_path %></li>
          <% if logged_in? %>
           <li><%=link_to "Students", students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>  
        </ul>
      </div>
    </div>
  </nav>
  <% if flash.any? %>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <span class="white-text">
            
                <% flash.each do |key, message| %>
                  <%= message %>
                <% end %>
              
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amenitiz Mentoring Program</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>